add Book table
SergeyGhazaryan/ShowSQLTables pull request #1
Opened 2021-01-12 23:38 UTC by SergeyGhazaryan

2021-01-13 14:21 UTC, Shitikyan requested changes

2021-01-13 14:21 UTC, Shitikyan commented on ShowSQLTables/Program.cs
>              using (SqlConnection connection = new SqlConnection(connectionString))
I cant see any classes used here

2021-01-13 14:21 UTC, Shitikyan commented on ShowSQLTables/Program.cs
> +                if (reader1.HasRows || reader2.HasRows)
incorrect check

2021-01-14 13:57 UTC, Ed467016 requested changes

2021-01-14 13:57 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +        public DataTable(SqlCommand command, SqlDataReader reader)
This class will be more safe and reusable if its getting query string and open conncetion/reader on its own. That way chances of failure will be much more lower. Add IDataStore interface for this class which will support Get operation

2021-01-14 13:57 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +                        Console.Write("{0} \t", property);
Dont print results but return them so the code outside can use the results for other sake rather then only printing. Think about reusability of this class

2021-01-15 14:50 UTC, Ed467016 requested changes

2021-01-15 14:50 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +        public List<object> DataTaker()
use generic

2021-01-15 14:50 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +        public DataTable(DataTbl dataTbl)
Initialize command and reader in this class and dont get it outside

2021-01-15 14:50 UTC, Ed467016 commented on ShowSQLTables/DataTbl.cs
> +    class DataTbl
bad class name

2021-01-15 14:50 UTC, Ed467016 commented on ShowSQLTables/IDataStore.cs
> +        DataTbl DataTbl { get; }
Store only methods in interface

2021-01-15 14:50 UTC, Ed467016 commented on ShowSQLTables/PrinterOfList.cs
> +    class PrinterOfList
This class doesnt make sense to me

2021-01-15 14:52 UTC, Shitikyan requested changes

2021-01-15 14:52 UTC, Shitikyan commented on ShowSQLTables/Program.cs
> +                SqlCommand command = new SqlCommand("SELECT * FROM Author", connection);
`SqlCommand` and `SqlDataReader` are disposable and they are allocating unmanaged resources to connect  the database. Please include also `IDisposable` implementation here.

2021-01-15 14:52 UTC, Shitikyan commented on ShowSQLTables/DataTbl.cs
> +    class DataTbl
What represents this class?

2021-01-15 14:52 UTC, Shitikyan commented on ShowSQLTables/PrinterOfList.cs
> +        public void Print()
If I say you need to use the BookPrice and show avg price of it  how this structure will handle it?

2021-01-18 14:04 UTC, Ed467016 requested changes

2021-01-18 14:04 UTC, edotnet commented on ShowSQLTables/DataTaker.cs
> +        public void Dispose(List<T> listOfProperty)
This is not needed

2021-01-18 14:04 UTC, edotnet commented on ShowSQLTables/DataTaker.cs
> +        public DataTable(SqlCommand command, SqlDataReader reader)
Last comment is not fixed yet

2021-01-18 14:04 UTC, Ed467016 commented on ShowSQLTables/IDisposable.cs
> +    interface IDisposable<T>
there is IDisposable interface in .net please use that one

2021-01-18 20:33 UTC, Ed467016 requested changes

2021-01-18 20:33 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +        public DataTable(string connectionString, string sqlExpression, SqlConnection connection)
remove sqlconnection

2021-01-19 20:02 UTC, Ed467016 requested changes

2021-01-19 20:02 UTC, edotnet commented on ShowSQLTables/DataTaker.cs
> +        public List<T> DataTaker(SqlConnection connection)
This function doesnt need connection parameter. It should create one based on connection string

2021-01-19 20:02 UTC, Ed467016 commented on ShowSQLTables/FunctionSelector.cs
> +
remove empty line

2021-01-19 20:02 UTC, Ed467016 commented on ShowSQLTables/FunctionSelector.cs
> +            connection.Dispose();
Take function into try catch and dispose connection in finally. Since if exception occurs the connection will remain open

2021-01-21 14:36 UTC, Ed467016 requested changes

2021-01-21 14:36 UTC, Ed467016 commented on ShowSQLTables/DataTaker.cs
> +        public List<object> DataTaker(SqlConnection connection)
Remove parameter, use generics

2021-01-29 15:28 UTC, merged