Add Generics
SergeyGhazaryan/ShowSQLTables pull request #2
Opened 2021-01-29 16:37 UTC by SergeyGhazaryan

2021-01-29 22:00 UTC, Shitikyan requested changes

2021-01-29 22:00 UTC, Shitikyan commented on ShowSQLTables/Author.cs
> +        public int ID { get; set; }
Use `Id` instead of `ID`

2021-01-29 22:00 UTC, Shitikyan commented on ShowSQLTables/Book.cs
> +        public int AuthorID { get; set; }
Use `AuthorId` instead of `AuthorID`

2021-01-31 20:32 UTC, Ed467016 approved these changes

2021-02-02 11:20 UTC, merged